#!/bin/bash
git config --global user.email "dkelertas@github.com" && git config --global user.name "David Kelertas"
/usr/local/bin/mise trust /workspaces/mise-container/mise.toml && /usr/local/bin/mise install
